# Generated by Django 3.2 on 2021-05-02 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20210430_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Новый пост', help_text='Введите заголовок поста', max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('author', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='viewing',
            unique_together={('post', 'user')},
        ),
    ]
